### ISSUE TITLE
Incorrect directory name

### ISSUE THREAD

**Issue by videopilot** [linuxgurugamer/FruitKocktail#1]
If I install this from CKAN, it gives an error on startup that the files are in the wrong directory.

It installs into:
FruitKocktail/VSIndicator

But gives an error that it should be in:
FruitKocktail/VertikalSpeedIndicator

**Comment by linuxgurugamer** [comment]
thanks, I'll get it updated.
It will work as is, however

**Comment by linuxgurugamer** [comment]
Should be fixed now

**Comment by videopilot** [comment]
Unfortunately, the toolbar texture is still looking for VertikalSpeedIndicator, it seems.

**Comment by linuxgurugamer** [comment]
Fixed.  VisualStudio search decided to fail when I did this
